name: Publish mcro.de
run-name: ${{ github.actor }} Publishing mcro.de
on:
  push:
    branches:
      - master
  workflow_call:
    secrets:
      MCRODE_DEPLOY_TOKEN:
        required: true
jobs:
  publish:
    permissions:
      contents: write
      pull-requests: write
      actions: read
    uses: microdee/echweb/.github/workflows/publish-site.yml@master
    with:
      content-repo: microdee/echweb-mcrode
      target-repo: microdee/microdee.github.io
      target-domain: mcro.de
      target-domain_var: mcro_de
    secrets:
      PAGES_DEPLOY_TOKEN: "${{ secrets.MCRODE_DEPLOY_TOKEN }}"